# Generated by Django 6.1 on 2026-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_staus_posts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='references',
            field=models.TextField(blank=True, default='', help_text='List the sources or links that support this fatwa.'),
        ),
    ]
