# Generated by Django 6.1 on 2026-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posts_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='references',
            field=models.CharField(blank=True, default='', help_text='List the sources or links that support this fatwa.', max_length=200),
        ),
    ]
