# Generated by Django 6.1 on 2026-09-08 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fatwas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=240)),
                ('original_body', models.TextField()),
                ('public_title', models.CharField(blank=True, max_length=240)),
                ('public_body', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('bn', 'Bangla'), ('en', 'English'), ('ar', 'Arabic')], max_length=2)),
                ('madhhab_preference', models.CharField(blank=True, max_length=120)),
                ('is_public', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('needs_clarification', 'Needs clarification'), ('answered', 'Answered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=24)),
                ('moderation_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_scholar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scholar_assignments', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='fatwas.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ClarificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clarifications', to='questions.question')),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['status', 'language'], name='questions_q_status_212af7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assigned_scholar', 'status'], name='questions_q_assigne_4a4b71_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['assigned_reviewer', 'status'], name='questions_q_assigne_7c686d_idx'),
        ),
    ]
