from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    AnswerCreateAPIView,
    AssignQuestionAPIView,
    BookmarkListCreateAPIView,
    CategoryListAPIView,
    HealthAPIView,
    LoginAPIView,
    LogoutAPIView,
    MeAPIView,
    ModerationQuestionListAPIView,
    MethodologyListAPIView,
    NotificationListAPIView,
    PublicFatwaDetailAPIView,
    PublicFatwaListAPIView,
    QuestionDetailAPIView,
    QuestionListCreateAPIView,
    RegisterAPIView,
    ReportCreateAPIView,
    ReviewActionAPIView,
    ReviewQueueAPIView,
    ScholarApplicationAPIView,
    ScholarAssignmentListAPIView,
    ScholarDetailAPIView,
    ScholarListAPIView,
    ScholarModerationActionAPIView,
    ScholarModerationListAPIView,
    VerifyEmailAPIView,
)


urlpatterns = [
    path('health/', HealthAPIView.as_view(), name='api-health'),
    path('auth/register/', RegisterAPIView.as_view(), name='api-register'),
    path('auth/token/', LoginAPIView.as_view(), name='api-token'),
    path('auth/login/', LoginAPIView.as_view(), name='api-login'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='api-token-refresh'),
    path('auth/logout/', LogoutAPIView.as_view(), name='api-logout'),
    path('auth/verify-email/<str:token>/', VerifyEmailAPIView.as_view(), name='api-verify-email'),
    path('me/', MeAPIView.as_view(), name='api-me'),
    path('me/scholar-profile/', ScholarApplicationAPIView.as_view(), name='api-scholar-application'),
    path('me/questions/', QuestionListCreateAPIView.as_view(), name='api-questions'),
    path('me/questions/<int:pk>/', QuestionDetailAPIView.as_view(), name='api-question-detail'),
    path('me/bookmarks/', BookmarkListCreateAPIView.as_view(), name='api-bookmarks'),
    path('me/notifications/', NotificationListAPIView.as_view(), name='api-notifications'),
    path('fatwas/', PublicFatwaListAPIView.as_view(), name='api-fatwas'),
    path('fatwas/<int:publication_id>/', PublicFatwaDetailAPIView.as_view(), name='api-fatwa-detail'),
    path('fatwas/<int:publication_id>/report/', ReportCreateAPIView.as_view(), name='api-report-fatwa'),
    path('categories/', CategoryListAPIView.as_view(), name='api-categories'),
    path('methodologies/', MethodologyListAPIView.as_view(), name='api-methodologies'),
    path('scholars/', ScholarListAPIView.as_view(), name='api-scholars'),
    path('scholars/<int:user_id>/', ScholarDetailAPIView.as_view(), name='api-scholar-detail'),
    path('scholar/assignments/', ScholarAssignmentListAPIView.as_view(), name='api-scholar-assignments'),
    path('scholar/questions/<int:question_id>/answer/', AnswerCreateAPIView.as_view(), name='api-answer'),
    path('reviews/', ReviewQueueAPIView.as_view(), name='api-review-queue'),
    path('reviews/<int:revision_id>/<str:action>/', ReviewActionAPIView.as_view(), name='api-review-action'),
    path('moderation/scholars/', ScholarModerationListAPIView.as_view(), name='api-moderation-scholars'),
    path('moderation/scholars/<int:user_id>/', ScholarModerationActionAPIView.as_view(), name='api-moderation-scholar-action'),
    path('moderation/questions/', ModerationQuestionListAPIView.as_view(), name='api-moderation-questions'),
    path('moderation/questions/<int:question_id>/assign/', AssignQuestionAPIView.as_view(), name='api-assign-question'),
]
