from django.urls import path

from api_views import (
    api_assign_question,
    api_bookmarks,
    api_categories,
    api_csrf,
    api_fatwa_detail,
    api_fatwas,
    api_login,
    api_logout,
    api_me,
    api_methodologies,
    api_notifications,
    api_question_detail,
    api_questions,
    api_review_action,
    api_review_queue,
    api_report_fatwa,
    api_scholar_assignments,
    api_scholar_detail,
    api_scholars,
    api_answer,
    api_register,
    api_verify_email,
)

urlpatterns = [
    path('auth/csrf/', api_csrf, name='api-csrf'),
    path('auth/register/', api_register, name='api-register'),
    path('auth/login/', api_login, name='api-login'),
    path('auth/logout/', api_logout, name='api-logout'),
    path('auth/verify-email/<str:token>/', api_verify_email, name='api-verify-email'),
    path('me/', api_me, name='api-me'),
    path('me/questions/', api_questions, name='api-questions'),
    path('me/questions/<int:question_id>/', api_question_detail, name='api-question-detail'),
    path('me/bookmarks/', api_bookmarks, name='api-bookmarks'),
    path('me/notifications/', api_notifications, name='api-notifications'),
    path('fatwas/', api_fatwas, name='api-fatwas'),
    path('fatwas/<int:publication_id>/', api_fatwa_detail, name='api-fatwa-detail'),
    path('fatwas/<int:publication_id>/report/', api_report_fatwa, name='api-report-fatwa'),
    path('categories/', api_categories, name='api-categories'),
    path('methodologies/', api_methodologies, name='api-methodologies'),
    path('scholars/', api_scholars, name='api-scholars'),
    path('scholars/<int:user_id>/', api_scholar_detail, name='api-scholar-detail'),
    path('scholar/assignments/', api_scholar_assignments, name='api-scholar-assignments'),
    path('scholar/questions/<int:question_id>/answer/', api_answer, name='api-answer'),
    path('reviews/', api_review_queue, name='api-review-queue'),
    path('reviews/<int:revision_id>/<str:action>/', api_review_action, name='api-review-action'),
    path('moderation/questions/<int:question_id>/assign/', api_assign_question, name='api-assign-question'),
]
