# Generated by Django 6.1 on 2026-09-08 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fatwas', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='answer', to='questions.question'),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='fatwas.answer'),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='fatwas.answerrevision'),
        ),
        migrations.AddField(
            model_name='answer',
            name='approved_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fatwas.answerrevision'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerrevision',
            name='methodology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='fatwas.methodology'),
        ),
        migrations.AddField(
            model_name='publication',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='publication', to='fatwas.answer'),
        ),
        migrations.AddField(
            model_name='publication',
            name='approved_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fatwas.answerrevision'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='fatwas.publication'),
        ),
        migrations.AddField(
            model_name='report',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='fatwas.publication'),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='fatwas.answerrevision'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['object_type', 'object_id'], name='fatwas_audi_object__bb2f94_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerrevision',
            constraint=models.UniqueConstraint(fields=('answer', 'revision_number'), name='unique_answer_revision'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'publication'), name='unique_user_bookmark'),
        ),
    ]
