# Generated by Django 6.1 on 2026-09-08 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatwas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
